install.packages('tidyverse', repos = "https://cran.us.r-project.org")
install.packages('gridExtra', repos = "https://cran.us.r-project.org")
install.packages('ModelMetrics', repos = "https://cran.us.r-project.org")
install.packages('caret', repos = "https://cran.us.r-project.org")
install.packages('reshape2', repos = "https://cran.us.r-project.org")
install.packages('pROC', repos = "https://cran.us.r-project.org")
install.packages('effsize', repos = "https://cran.us.r-project.org")
install.packages('ScottKnottESD', repos = "https://cran.us.r-project.org")